name: build angular app to test artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3.5.1

      - name: install dependencies
        run: |
          npm install

      - name: build app
        run: |
          npm run build

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./dist/testingGrounds

  open_artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifact from build step
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Read artifact
        run: |
          ls
